# Generated by Django 3.1.1 on 2024-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_pattern', models.CharField(blank=True, choices=[('r', 'Random'), ('c', 'Chronological')], default='r', help_text='Display patterns', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for the image.', max_length=100, unique=True)),
                ('time_date', models.DateTimeField()),
                ('description', models.CharField(help_text='Enter image description.', max_length=250)),
                ('img_link', models.CharField(max_length=200)),
            ],
        ),
    ]
