# Generated by Django 3.1.1 on 2024-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name for tag', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_link',
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(help_text='select tags for image', to='users.Tags'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(help_text='Choose tags for image', to='users.Tags'),
        ),
    ]
