# Generated by Django 3.1.1 on 2024-04-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_image_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.FileField(null=True, upload_to='image_uploads'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(default='place holder', help_text='Image link here', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='time_date',
            field=models.DateField(),
        ),
    ]
