# Generated by Django 3.1.1 on 2024-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240502_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(help_text='Enter image description.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.CharField(default='place holder', help_text='Image link here', max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(help_text='Choose tags for image', to='users.Tags'),
        ),
        migrations.AddField(
            model_name='image',
            name='time_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(null=True, upload_to='image_uploads'),
        ),
    ]
