# Generated by Django 3.1.1 on 2024-05-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240502_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(default='place holder', help_text='Image link here', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(default='place holder', help_text='Image id here', max_length=500),
        ),
    ]
