# Generated by Django 3.1.1 on 2024-05-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240508_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.CharField(default='place holder', help_text='Image link here', max_length=2000),
        ),
    ]
